// Generated by tools/randolocke/gen_tm_tiers.py. Do not edit by hand.
//
// The 50 real TMs, grouped by the tier of the move each one teaches, so a TM drop
// can be weighted exactly like a move roll.
//
// ITEM_TM51..ITEM_TM100 exist as constants but are unassigned placeholders
// (name "TM51", description "?????"), so they are deliberately not included.

// MetaDefining -- 1 TMs
static const u16 sTmTierMetaDefining[] =
{
    ITEM_TM_PROTECT,
};

// Staples -- 5 TMs
static const u16 sTmTierStaples[] =
{
    ITEM_TM_BULK_UP,
    ITEM_TM_GIGA_DRAIN,
    ITEM_TM_EARTHQUAKE,
    ITEM_TM_SHADOW_BALL,
    ITEM_TM_FACADE,
};

// Filler -- 19 TMs
static const u16 sTmTierFiller[] =
{
    ITEM_TM_DRAGON_CLAW,
    ITEM_TM_TOXIC,
    ITEM_TM_BULLET_SEED,
    ITEM_TM_TAUNT,
    ITEM_TM_ICE_BEAM,
    ITEM_TM_BLIZZARD,
    ITEM_TM_HYPER_BEAM,
    ITEM_TM_LIGHT_SCREEN,
    ITEM_TM_FRUSTRATION,
    ITEM_TM_THUNDERBOLT,
    ITEM_TM_RETURN,
    ITEM_TM_DIG,
    ITEM_TM_BRICK_BREAK,
    ITEM_TM_FLAMETHROWER,
    ITEM_TM_FIRE_BLAST,
    ITEM_TM_AERIAL_ACE,
    ITEM_TM_TORMENT,
    ITEM_TM_REST,
    ITEM_TM_OVERHEAT,
};

// Niche -- 15 TMs
static const u16 sTmTierNiche[] =
{
    ITEM_TM_FOCUS_PUNCH,
    ITEM_TM_CALM_MIND,
    ITEM_TM_ROAR,
    ITEM_TM_SUNNY_DAY,
    ITEM_TM_RAIN_DANCE,
    ITEM_TM_SAFEGUARD,
    ITEM_TM_SOLAR_BEAM,
    ITEM_TM_IRON_TAIL,
    ITEM_TM_THUNDER,
    ITEM_TM_REFLECT,
    ITEM_TM_SANDSTORM,
    ITEM_TM_ROCK_TOMB,
    ITEM_TM_SECRET_POWER,
    ITEM_TM_THIEF,
    ITEM_TM_STEEL_WING,
};

// Bad -- 9 TMs
static const u16 sTmTierBad[] =
{
    ITEM_TM_WATER_PULSE,
    ITEM_TM_HAIL,
    ITEM_TM_HIDDEN_POWER,
    ITEM_TM_PSYCHIC,
    ITEM_TM_SHOCK_WAVE,
    ITEM_TM_SLUDGE_BOMB,
    ITEM_TM_ATTRACT,
    ITEM_TM_SKILL_SWAP,
    ITEM_TM_SNATCH,
};

// Homeless -- 1 TMs
static const u16 sTmTierHomeless[] =
{
    ITEM_TM_DOUBLE_TEAM,
};
