#!/usr/bin/env python3
"""Generate src/data/randomizer/ability_tiers.h from docs/tiering/ABILITIES_BY_TIER.md.

Run validate_tiers.py first; this refuses to write if anything is unresolved.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from validate_tiers import ROOT, constants, normalise, parse, EXCLUDED  # noqa: E402

ORDER = ["S", "A", "B", "C", "D", "F", "Negative"]
OUT = ROOT / "src/data/randomizer/ability_tiers.h"


def main() -> int:
    valid = constants("include/constants/abilities.h", "ABILITY_")
    tiers = parse(ROOT / "docs/tiering/ABILITIES_BY_TIER.md")

    resolved, bad = {}, []
    for tier in ORDER:
        resolved[tier] = []
        for name in tiers.get(tier, []):
            c = normalise(name)
            if c not in valid:
                bad.append((tier, name))
            elif c in EXCLUDED:
                continue
            else:
                resolved[tier].append(c)
    if bad:
        print("refusing to generate; run validate_tiers.py:", bad)
        return 1

    covered = {c for v in resolved.values() for c in v} | EXCLUDED
    missing = sorted(valid - covered)

    L = []
    L.append("// Generated by tools/randolocke/gen_ability_tiers.py from")
    L.append("// docs/tiering/ABILITIES_BY_TIER.md. Do not edit by hand.")
    L.append("//")
    L.append("// Source: docs/tiering/community-abilities-tierlist.png (community-voted).")
    L.append(f"// Covers {len(covered)} of {len(valid)} abilities in this ROM.")
    L.append("//")
    L.append("// Excluded and never rolled: " + ", ".join(sorted("ABILITY_" + e for e in EXCLUDED)))
    L.append("")
    for tier in ORDER:
        names = resolved[tier]
        L.append(f"// Tier {tier} -- {len(names)} abilities")
        L.append(f"static const u16 sAbilityTier{tier}[] =")
        L.append("{")
        L += [f"    ABILITY_{c}," for c in names]
        L.append("};")
        L.append("")
    L.append(f"// {len(missing)} abilities appear in no tier. Until they are classified they are")
    L.append("// unreachable, so RZ_ABILITY_UNTIERED_FALLBACK decides where they land.")
    L.append("static const u16 sAbilityUntiered[] =")
    L.append("{")
    L += [f"    ABILITY_{c}," for c in missing]
    L.append("};")
    L.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(L))
    print(f"wrote {OUT.relative_to(ROOT)}")
    for tier in ORDER:
        print(f"  {tier:<9} {len(resolved[tier]):>3}")
    print(f"  untiered  {len(missing):>3}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
