#!/usr/bin/env python3
"""Generate src/data/randomizer/berry_tiers.h.

Berries are randomized at berry trees rather than in the field-item pool, so they need
their own tiers. The 43 hand-graded in pokeemerald_rando_enh are authoritative; 1.17 has
68, and the rest are placed by hold effect - the line the item data itself draws.

Nuzlocke logic applies as elsewhere: in-battle healing is close to worthless in a run that
uses a cheat heal item, so pinch-berry stat boosts and status cures outrank HP restoration.
"""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
FORK = Path("/Users/azima/Desktop/Python_Fun_Scripts/pokeemerald_rando_enh")
OUT = ROOT / "src/data/randomizer/berry_tiers.h"
TIERS = 5

# Hold effects that matter in a fight, best first. Anything unlisted with a hold effect
# lands in tier 3; anything with no hold effect at all lands in tier 5.
BY_HOLD_EFFECT = {
    "HOLD_EFFECT_CURE_STATUS": 0,       # Lum: cures anything
    "HOLD_EFFECT_RESTORE_HP": 0,        # Sitrus
    "HOLD_EFFECT_SPEED_UP": 0,          # Salac
    "HOLD_EFFECT_ATTACK_UP": 0,         # Liechi
    "HOLD_EFFECT_SP_ATTACK_UP": 0,      # Petaya
    "HOLD_EFFECT_DEFENSE_UP": 1,
    "HOLD_EFFECT_SP_DEFENSE_UP": 1,
    "HOLD_EFFECT_CRITICAL_UP": 1,       # Lansat
    "HOLD_EFFECT_RANDOM_STAT_UP": 1,    # Starf
    "HOLD_EFFECT_RESTORE_PP": 1,        # Leppa
    "HOLD_EFFECT_CURE_SLP": 2,
    "HOLD_EFFECT_CURE_PSN": 2,
    "HOLD_EFFECT_CURE_BRN": 2,
    "HOLD_EFFECT_CURE_PAR": 2,
    "HOLD_EFFECT_CURE_FRZ": 2,
    "HOLD_EFFECT_CURE_CONFUSION": 2,
    "HOLD_EFFECT_CURE_ATTRACT": 3,
    "HOLD_EFFECT_RESTORE_HP_QUARTER": 2,
}


def berries() -> list[tuple[str, str]]:
    s = (ROOT / "src/data/items.h").read_text()
    out = []
    for name, body in re.findall(r"\[(ITEM_[A-Z0-9_]+)\]\s*=\s*\{(.*?)\n    \},", s, re.S):
        if not re.search(r"\.pocket\s*=\s*POCKET_BERRIES", body):
            continue
        m = re.search(r"\.holdEffect\s*=\s*(\w+)", body)
        out.append((name, m.group(1) if m else "HOLD_EFFECT_NONE"))
    return out


def hand_tiers() -> dict[str, int]:
    path = FORK / "src/data/pokemon/berry_tiers.h"
    if not path.exists():
        return {}
    s = path.read_text()
    out = {}
    for tier, body in re.findall(r"sBerryTier(\d)\[\] =\s*\{(.*?)\};", s, re.S):
        for line in body.split("\n"):
            line = line.strip().rstrip(",")
            if line.startswith("ITEM_"):
                out[line] = int(tier) - 1
    return out


def main() -> int:
    all_berries = berries()
    hand = hand_tiers()
    tiers: list[list[str]] = [[] for _ in range(TIERS)]
    by_hand = by_heur = 0

    for name, hold in all_berries:
        if name in hand:
            tiers[hand[name]].append(name); by_hand += 1
        elif hold == "HOLD_EFFECT_NONE":
            tiers[4].append(name); by_heur += 1
        else:
            tiers[BY_HOLD_EFFECT.get(hold, 2)].append(name); by_heur += 1

    L = ["// Generated by tools/randolocke/gen_berry_tiers.py. Do not edit by hand.",
         "//",
         "// Berries are randomized at berry trees, not in the field-item pool, so they carry",
         "// their own tiers. Hand grades from pokeemerald_rando_enh are authoritative; the",
         "// rest are placed by hold effect, the line the item data itself draws.",
         "//",
         f"// {len(all_berries)} berries: {by_hand} hand-graded, {by_heur} by hold effect.",
         ""]
    for i, names in enumerate(tiers, 1):
        L.append(f"// Tier {i} -- {len(names)} berries")
        L.append(f"static const u16 sBerryTier{i}[] =")
        L.append("{")
        L += [f"    {n}," for n in names] or ["    ITEM_NONE,"]
        L.append("};")
        L.append("")
    OUT.write_text("\n".join(L))
    print(f"wrote {OUT.relative_to(ROOT)}")
    print(f"  {len(all_berries)} berries: {by_hand} hand-graded, {by_heur} by hold effect")
    for i, n in enumerate(tiers, 1):
        print(f"  tier {i}: {len(n)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
