#!/usr/bin/env python3
"""Generate src/data/randomizer/tm_tiers.h: the TM items grouped by the tier of the move
they teach, so a TM drop can be weighted the same way a move roll is.

Only the 50 real TMs are included. ITEM_TM51..ITEM_TM100 exist as constants but are
unassigned placeholders (name "TM51", description "?????"), so rolling them would hand the
player a TM that teaches nothing.
"""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "src/data/randomizer/tm_tiers.h"
ORDER = ["MetaDefining", "Staples", "Filler", "Niche", "Bad", "Homeless"]


def main() -> int:
    s = (ROOT / "include/constants/tms_hms.h").read_text()
    body = re.search(r"#define FOREACH_TM\(F\)(.*?)\n\n", s, re.S).group(1)
    tms = re.findall(r"F\((\w+)\)", body)

    mt = (ROOT / "src/data/randomizer/move_tiers.h").read_text()
    tier_of = {}
    for name, blk in re.findall(r"sMoveTier(\w+)\[\] =\s*\{(.*?)\};", mt, re.S):
        for line in blk.split("\n"):
            line = line.strip().rstrip(",")
            if line.startswith("MOVE_"):
                tier_of[line[5:]] = name

    groups = {t: [] for t in ORDER}
    unknown = []
    for tm in tms:
        t = tier_of.get(tm)
        (groups[t] if t else unknown).append(tm)

    L = ["// Generated by tools/randolocke/gen_tm_tiers.py. Do not edit by hand.",
         "//",
         "// The 50 real TMs, grouped by the tier of the move each one teaches, so a TM drop",
         "// can be weighted exactly like a move roll.",
         "//",
         "// ITEM_TM51..ITEM_TM100 exist as constants but are unassigned placeholders",
         '// (name "TM51", description "?????"), so they are deliberately not included.',
         ""]
    for t in ORDER:
        names = groups[t]
        L.append(f"// {t} -- {len(names)} TMs")
        L.append(f"static const u16 sTmTier{t}[] =")
        L.append("{")
        L += [f"    ITEM_TM_{n}," for n in names] or ["    ITEM_NONE,"]
        L.append("};")
        L.append("")
    OUT.write_text("\n".join(L))
    print(f"wrote {OUT.relative_to(ROOT)}")
    for t in ORDER:
        print(f"  {t:<14} {len(groups[t]):>3}")
    if unknown:
        print("  untiered TMs:", unknown)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
