#!/usr/bin/env python3
"""Generate src/data/randomizer/move_tiers.h from docs/tiering/MOVES_BY_TIER_RANDOLOCKE.md.

Run validate_tiers.py --moves first; this refuses to write if anything is unresolved.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from validate_tiers import (ROOT, constants, normalise, parse, POOLS,  # noqa: E402
                            MOVES_EXCLUDED, MOVES_PUSHDOWN, z_and_max_moves)

ORDER = ["Meta Defining", "Staples", "Filler/Outclassed", "Niche", "Bad", "Pokemon Homeless"]
IDENT = {"Meta Defining": "MetaDefining", "Staples": "Staples",
         "Filler/Outclassed": "Filler", "Niche": "Niche", "Bad": "Bad",
         "Pokemon Homeless": "Homeless"}
OUT = ROOT / "src/data/randomizer/move_tiers.h"


def main() -> int:
    header, prefix, sheet = POOLS["moves"]
    valid = constants(header, prefix)
    tiers = parse(ROOT / sheet)
    excluded = MOVES_EXCLUDED | z_and_max_moves()
    bottom = ORDER[-1]

    resolved = {t: [] for t in ORDER}
    bad, pushed = [], 0
    for tier in ORDER:
        for name in tiers.get(tier, []):
            c = normalise(name)
            if c not in valid:
                bad.append((tier, name))
                continue
            if c in excluded:
                continue
            if c in MOVES_PUSHDOWN and tier != bottom:
                resolved[bottom].append(c)
                pushed += 1
            else:
                resolved[tier].append(c)
    if bad:
        print("refusing to generate; run validate_tiers.py --moves:", bad)
        return 1

    covered = {c for v in resolved.values() for c in v}
    missing = sorted(valid - covered - excluded)

    L = ["// Generated by tools/randolocke/gen_move_tiers.py from",
         f"// {sheet}. Do not edit by hand.",
         "//",
         "// Source: docs/tiering/community-moves-tierlist.png (community-voted).",
         f"// {len(covered)} rollable moves tiered; {len(excluded & valid)} excluded",
         "// (Z / Max / G-Max moves and Struggle).",
         "//",
         f"// {pushed} self-KO and OHKO moves were pushed to the bottom band for nuzlocke",
         "// play; see MOVES_PUSHDOWN in tools/randolocke/validate_tiers.py.",
         ""]
    for tier in ORDER:
        names = resolved[tier]
        L.append(f"// {tier} -- {len(names)} moves")
        L.append(f"static const u16 sMoveTier{IDENT[tier]}[] =")
        L.append("{")
        L += [f"    MOVE_{c}," for c in names]
        L.append("};")
        L.append("")
    L.append(f"// {len(missing)} rollable moves appear in no tier and are currently unreachable.")
    L.append("static const u16 sMoveUntiered[] =")
    L.append("{")
    L += [f"    MOVE_{c}," for c in missing] or ["    MOVE_NONE,"]
    L.append("};")
    L.append("")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(L))
    print(f"wrote {OUT.relative_to(ROOT)}")
    for t in ORDER:
        print(f"  {t:<20} {len(resolved[t]):>4}")
    print(f"  {'untiered':<20} {len(missing):>4}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
